----------------------------------------------------Lib's----------------------------------------------------------------------------------
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/advancedLua.lua /lib/advancedLua.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/color.lua /lib/color.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/modemConnection.lua /lib/modemConnection.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/unixtime.lua /lib/unixtime.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/OCIF.lua /lib/OCIF.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/GUI.lua /lib/GUI.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/image.lua /lib/image.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/doubleBuffering.lua /lib/doubleBuffering.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/bridge.lua /lib/bridge.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/colorlib.lua /lib/colorlib.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/web.lua /lib/web.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/event.lua /lib/event.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/internet.lua /lib/internet.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/archive.lua /lib/archive.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/SHA2.lua /lib/SHA2.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/ECSAPI.lua /lib/ECSAPI.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/bit32.lua /lib/bit32.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/context.lua /lib/context.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Lib/xmlParser.lua /lib/xmlParser.lua")
-------------------------------------------------------Img's---------------------------------------------------------------------------------
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/IconsPic/Floppy.pic /bin/Floppy.pic")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/IconsPic/HDD.pic /bin/HDD.pic")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/IconsPic/Update.pic /bin/Update.pic")
-----------------------------------------------------SYS FILE'S-------------------------------------------------------------------------------
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/autorun.lua /autorun.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/GUIE.lua /GUIE.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Apps/Snake.lua /bin/Snake.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Apps/flappybird.lua /bin/flappybird.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/Apps/Control.lua /bin/Control.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/rm-rf*.lua /bin/rm-rf.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/fileman.lua /fileman.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/AppShop.lua /AppShop.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/init.lua /init.lua")
  os.execute("wget -f https://raw.githubusercontent.com/matvey-mayner/OpenPenguin/main/SYS32.lua /SYS32.lua")
